# Generated by Django 4.2.7 on 2026-01-16 05:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'General User'), ('hospital', 'Hospital Admin'), ('ambulance', 'Ambulance Provider'), ('superuser', 'System Administrator')], default='user', max_length=20)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('hospital_address', models.TextField(blank=True)),
                ('hospital_city', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='private', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('beds_icu', models.IntegerField(default=0, verbose_name='ICU Beds')),
                ('beds_oxygen', models.IntegerField(default=0, verbose_name='Oxygen Beds')),
                ('beds_ventilator', models.IntegerField(default=0, verbose_name='Ventilators')),
                ('beds_isolation', models.IntegerField(default=0, verbose_name='Isolation Beds')),
                ('beds_total', models.IntegerField(default=0, verbose_name='Total Beds')),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities')),
                ('pricing_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_area', models.TextField(help_text='Comma-separated list of cities served')),
                ('pricing_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ambulance Provider',
                'verbose_name_plural': 'Ambulance Providers',
                'db_table': 'ambulance_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('basic', 'Basic Life Support (BLS)'), ('advanced', 'Advanced Life Support (ALS)'), ('icu', 'ICU Ambulance'), ('neonatal', 'Neonatal Ambulance')], max_length=20)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='core.ambulanceprovider')),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
                'db_table': 'ambulances',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
