# Generated by Django 4.2.7 on 2026-01-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='facilities',
            field=models.TextField(blank=True, help_text='Comma-separated list of facilities'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Currently Available'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='type',
            field=models.CharField(choices=[('ALS', 'Advanced Life Support'), ('BLS', 'Basic Life Support'), ('Non-Emergency', 'Non-Emergency')], max_length=20),
        ),
    ]
