# Generated by Django 4.2.7 on 2026-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ambulance_facilities_ambulance_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
    ]
