# Generated by Django 4.2.7 on 2026-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds_icu_capacity',
            field=models.IntegerField(default=0, verbose_name='ICU Beds (Total Capacity)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='beds_isolation_capacity',
            field=models.IntegerField(default=0, verbose_name='Isolation Beds (Total Capacity)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='beds_oxygen_capacity',
            field=models.IntegerField(default=0, verbose_name='Oxygen Beds (Total Capacity)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='beds_total_capacity',
            field=models.IntegerField(default=0, verbose_name='Total Beds (Total Capacity)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='beds_ventilator_capacity',
            field=models.IntegerField(default=0, verbose_name='Ventilators (Total Capacity)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
