# Generated by Django 4.2.7 on 2026-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_beds_icu_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='insurances',
            field=models.TextField(blank=True, help_text='Comma-separated list of accepted insurance providers'),
        ),
    ]
