# Generated by Django 4.2.7 on 2026-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hospital_insurances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='insurances',
        ),
        migrations.AddField(
            model_name='hospital',
            name='insurance_providers',
            field=models.JSONField(blank=True, default=dict, help_text='Accepted insurance providers'),
        ),
    ]
