# Generated by Django 4.2.7 on 2026-01-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_hospital_insurances_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                ],
                default="email_verification",
                max_length=20,
            ),
        ),
    ]
